apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "frigate.fullname" . }}
  labels:
{{ include "frigate.labels" . | indent 4 }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: {{ .Values.strategyType }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "frigate.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "frigate.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- if .Values.podAnnotations }}
        {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      {{- end }}
    spec:
      {{- if and .Values.gpu.nvidia.enabled (.Values.gpu.nvidia.runtimeClassName) }}
      runtimeClassName: {{ .Values.gpu.nvidia.runtimeClassName }}
      {{- end }}
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
    {{- end }}
    {{- if or .Values.extraInitContainers (and .Values.persistence.config.enabled .Values.persistence.config.ephemeralWritableConfigYaml) }}
      initContainers:
      {{- with .Values.extraInitContainers }}
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- if and .Values.persistence.config.enabled .Values.persistence.config.ephemeralWritableConfigYaml }}
        - name: copyconfig
          image: "{{ .Values.image.repository }}:{{ include "frigate.imageTag" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: /config.yml
              subPath: config.yml
              name: configmap
            - mountPath: /config
              name: config
          command: [ "cp" ]
          args: [ "-v", "/config.yml", "/config/config.yml" ]
      {{- end }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ include "frigate.imageTag" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- if and .Values.coral.enabled (not .Values.securityContext) }}
            privileged: true
            {{- else }}
            {{- toYaml .Values.securityContext | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
            - name: http-auth
              containerPort: 8971
              protocol: TCP
            - name: rtmp
              containerPort: 1935
              protocol: TCP
            - name: rtsp
              containerPort: 8554
              protocol: TCP
            - name: webrtc-udp
              containerPort: 8555
              protocol: UDP
            - name: webrtc-tcp
              containerPort: 8555
              protocol: TCP
            - name: go2rtc-admin
              containerPort: 1984
              protocol: TCP
          {{- if .Values.probes.liveness.enabled }}
          livenessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
          {{- end }}
          {{- if .Values.probes.readiness.enabled }}
          readinessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
          {{- end }}
          {{- if .Values.probes.startup.enabled }}
          startupProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            failureThreshold: {{ .Values.probes.startup.failureThreshold }}
            periodSeconds: {{ .Values.probes.startup.periodSeconds }}
          {{- end }}
          env:
            {{- if .Values.gpu.nvidia.enabled }}
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: "all"
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all"
            {{- end }}
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          envFrom:
          {{- range .Values.envFromSecrets }}
            - secretRef:
                name: {{ . }}
          {{- end }}
          volumeMounts:
            {{- if .Values.coral.enabled }}
            - mountPath: {{ .Values.coral.hostPath }}
              name: coral-dev
            {{- end }}
            {{- if not (and .Values.persistence.config.enabled .Values.persistence.config.ephemeralWritableConfigYaml) }}
            - mountPath: /config/config.yml
              subPath: config.yml
              name: configmap
            {{- end }}
            - mountPath: /config
              name: config
            - mountPath: /data
              name: data
            - mountPath: /media
              name: media
            - name: dshm
              mountPath: /dev/shm
            {{- if .Values.tmpfs.enabled }}
            - name: tmp
              mountPath: /tmp
            {{- end }}
            {{- if .Values.extraVolumeMounts }}{{ toYaml .Values.extraVolumeMounts | trim | nindent 12 }}{{ end }}
          resources:
            {{- include "frigate.resources" . | nindent 12 }}
      volumes:
        - name: configmap
          configMap:
            name: {{ template "frigate.fullname" . }}
        {{- if .Values.coral.enabled }}
        - name: coral-dev
          hostPath:
            path: {{ .Values.coral.hostPath }}
        {{- end }}
        - name: config
        {{- if .Values.persistence.config.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.config.existingClaim }}{{ .Values.persistence.config.existingClaim }}{{- else }}{{ template "frigate.fullname" . }}-config{{- end }}
        {{- else }}
          emptyDir: {}
        {{- end }}
        - name: data
        {{- if .Values.persistence.data.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.data.existingClaim }}{{ .Values.persistence.data.existingClaim }}{{- else }}{{ template "frigate.fullname" . }}-data{{- end }}
        {{- else }}
          emptyDir: {}
        {{- end }}
        - name: media
        {{- if .Values.persistence.media.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.media.existingClaim }}{{ .Values.persistence.media.existingClaim }}{{- else }}{{ template "frigate.fullname" . }}-media{{- end }}
        {{- else }}
          emptyDir: {}
        {{- end }}
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: {{ .Values.shmSize }}
        {{- if .Values.tmpfs.enabled }}
        - name: tmp
          emptyDir:
            medium: Memory
            sizeLimit: {{ .Values.tmpfs.sizeLimit }}
        {{- end }}
        {{- if .Values.extraVolumes  }}{{ toYaml .Values.extraVolumes | trim | nindent 8 }}{{ end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
