apiVersion: v1
kind: Service
metadata:
  name: {{ template "frigate.fullname" . }}
  labels:
{{ include "frigate.labels" . | indent 4 }}
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{- end }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if (or (eq .Values.service.type "ClusterIP") (empty .Values.service.type)) }}
  type: ClusterIP
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{end}}
{{- else if eq .Values.service.type "LoadBalancer" }}
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.service.loadBalancerSourceRanges | indent 4 }}
  {{- end -}}
{{- else }}
  type: {{ .Values.service.type }}
{{- end }}
  ipFamilyPolicy: {{ .Values.service.ipFamilyPolicy }}
  {{- if .Values.service.ipFamilies }}
  ipFamilies:
  {{- range .Values.service.ipFamilies }}
    - {{ . }}
  {{- end }}
  {{- end }}
{{- if .Values.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.service.externalIPs | indent 4 }}
{{- end }}
  {{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: http
{{ if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort))) }}
      nodePort: {{.Values.service.nodePort}}
{{ end }}
    - name: http-auth
      port: 8971
      protocol: TCP
      targetPort: http-auth
    - name: rtmp
      port: 1935
      protocol: TCP
      targetPort: rtmp
{{ if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort))) }}
      nodePort: {{.Values.service.nodePort}}
{{ end }}
    - name: rtsp
      port: 8554
      protocol: TCP
      targetPort: rtsp
      {{/* TODO: think of making the nodePort ability available, the rtmp solution from above would not work as you can't use the same port multiple times */}}
    - name: webrtc-tcp
      port: 8555
      protocol: TCP
      targetPort: webrtc-tcp
    - name: webrtc-udp
      port: 8555
      protocol: UDP
      targetPort: webrtc-udp
  selector:
    app.kubernetes.io/name: {{ include "frigate.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
